### ISSUE TITLE
Create application icon for OpenCine

### ISSUE THREAD

**Issue by BAndiT1983** [apertus-open-source-cinema/opencine#25]
Something interesting and not only plain O and C. Maybe something with camera shutter.

Consider size because of today monitors and resolutions. Reference: http://msdn.microsoft.com/en-us/library/windows/desktop/dn742485%28v=vs.85%29.aspx

**Comment by revast** [comment]
I like these ones, are under CC:
http://s0u1seeker.deviantart.com/art/Camera-Shutter-Logo-Concept-456996845

**Comment by BAndiT1983** [comment]
If you are experienced with graphics applications you could make a draft.

**Comment by BAndiT1983** [comment]
Moved issue to Lab.
