### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by subspacefield** [apertus-open-source-cinema/opencine#57]
Please update the build instructions, I had the following issues:
- OpenCL headers and library are required
- the clone command in the build instructions does not download lodepng

**Comment by BAndiT1983** [comment]
Hi @subspacefield, really sorry for late reply, we were rather busy with GSoC and other stuff. Which OS do you use and which version? 

I suppose that the build instructions miss the info about initializing linked repos. Will try to check it out.

**Comment by subspacefield** [comment]
I am building on Windows 10.
